// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PctpL+K6jZfXCqRpc4cR70tLYcyTrrHKssO9kqHxcLQ/bMICIBBgRlya7571u4",
	"kSAJcDhXjRI/pCIPgW6g++sbCIDfRjHLckaBimJ09m1UxHPIsPoTx4LcEfEg/845y4ELAvpJnl+9ln+I",
	"hxxGZ6NCcEJno/Ho/ojhnBzFLIEZ0CO4FxwfCTxTvf4sGB2dyc4RSUaLxVj+mZIYC8Lov3EGG1C0ZCIq",
	"6Uja8RxTCukmdA0Jh2aKi8KhRqiAGfCRfMQBC0g+qMdTxjMsRmejBAs4EiSD0Xi1ESQTyV/TjEQxGldj",
	"qn+TI5pxVm6gC9XdakP9YxN5aWqVtEjSJSR/poXANIb1R20p2IEXcAfcALWrmTvgBZH9OmNZjEcc/ioJ",
	"h2R09kmOd2ygXQvW1awFgMOxJt9FsyvRJh4bQvhcQYNN/oRYyDFb07vGM/CYn35q/kUEZOqP/+YwHZ2N",
	"/uuktugTY84nlS0vKm6Yc6z+HbOSCr/sBBM4PQ89b8nPaWyJjt2xeiea5+eMTsmsO8sEipiTXPh1Nx5R",
	"L1IXY0kmKWMRafzRMk3xJIXRmeAljJdgQBENDNQqtztUo9vh6jAdvNrYriPxu41lslXAHT4d1dw3mSUu",
	"oPCIciDYdDufppbh4ipZ1+84wFp4nQfVxu1Kt+k/jFzHNWJcYbhDDGCwCHiEGp0r+AQH0nt3C+6AvXPl",
	"8TwQaY3t9Alho+ykyiVslmKG0itL2UYJLWXci7692HXA3qxJZPj+LdCZmI/OXpyOPRaC41uDr77J2mZ1",
	"j/XlbQgstSkt2KY1NRXuDsYorQOsQVmX9c011kIhqgUWn+gDOJYDmbEj82tJqOhHT9ip1fJbmuC0hmsG",
	"V8s2GPyMGPy+Z6vBb5c+pxqod4ohFccxFMVvmOIZZEDFR56u7VoUqSiraEUl1zDDpZj/xpL1C6BSzKNM",
	"EpDU5oAT4DfiIV2boCYRFYqGpJmyGaEbzF31r+abshnbgBJTRChMOC5u8e+h/H4YPUsmsom8pM1IEr8s",
	"EwI0XluGkkaELRFL9TwlQDfIQRTVWBGx8Un+dFUUJfANFKToEkWlUpP87S2bsVJsSjhVVBqEb2KWQ7ER",
	"1UKTkBQFEeujXXfuhB+f6XdhZ9Bsh9A0P8dwHCv3+R/gnPH3UOSMFrC0GGr8c/SmzDA94oATWeggRQo1",
	"k9BO3EhY3CU8ekvoLRIMJSwu5ZRVrEDPmHqO0x98lBS7Lqlf1Sik3BFJgAoyJSru9YcoTayZQnvFJfV4",
	"QdJWCdwU2hwXc2/QlA+ev/jFX5sk/vgTjMAF+Qr+2NsZdSPcDcOm+jGaqplKmtMUixjzl3GoEuUsg3c3",
	"GzpFTYYVDae4p8oUJymhflEnpJAIv8YPKcPJKxzfsunUaTlhLAVMB3I21KJck4smhp4cBtxBI9EI4MP5",
	"uXgNqcBrD4YUUaIISO4ZCJxggW/IjGJRcnhf4HVVaWlFhSUW8aLN5itsgfxXMHEZkuJlkhG6tjAUiQgr",
	"GmqBb4795uorGLTqxh1TqMg0hlhrLgSvgDpa4nOQ61rKqhWIEYCx8ghrM+8Y/nVdqDXtP4DOPgFuaXx6",
	"DWhvRbmzCjCw1jB/rj8K+zrAjuAQFuqmjMfwMZdci1+pRG/fgPrXQgeqXnKMSs0yAs1z4PpDt3plKYkf",
	"fsP3ZgrXwK+BE6bIZISSrMxGZ/VShVs+D1hbUNSjDN9X482By/8kh0XF/910SmJ4w0perO2yDC+mSEVz",
	"RavmoCd1RQXwO7x2Km146PFHxFKr2dzgKbTqyLVmUeAp1PWk/vEDyeAro7Dh4IUlU1PWupf0WSk2JK/1",
	"rLhIYm0m1kY2FVAL/joQsTRlpbii15zNOBTrY8lQigiNcktLeWqO41uvHZnxvNYBLHldwgd2gUla8vWx",
	"YOdoomISJSVEgkVTQ3fNJfCumPqHH/Jx3eW/2sEHlN4xE58D6OA9YMN9zsuPbKtAXz2jomdomdEJPN6s",
	"uBkjnEXe595V3sGrwb3u01sk+bxgF391w7YrC8cIxyf1ERRBL1W3afmIpS1rM/dyrqyyIfhfBr1pXCbk",
	"oKC6Ew5NL4i2K/Pe6UZg4X0Rl+UpCPArOmFfqEySIel/LmfubVCtGnQfqRdiaRoizegbliY9i8T+RyVN",
	"YEpoiKqW2iXHVHibrOIzo5khs/CuS4/cwbQ5j6slkEoBrkQakm+KuZJMUOOB9fvwmvu2XgNvvnZvRhKc",
	"mgRxWahe0t22VhCc2qZ+6ZLh/JM0kmPZ4bP8F6FC/V9b7OeSUPHLzxULU0e+4oBvpdwHi+Wu1fFXKrh3",
	"I4bLZsOpdKZg3zJ7KrSU4ML/7qq556Fvjpb8y+Y75cd86UnygQsGJO8v2R3pvezbBbKzUncfQtzmRrLt",
	"7/BKcSHO5xDfXjBusq2tCkPSj2LJIJoybiNxxfqj66I/7IB1M25YndSsN1zOdXm4K7qF8pp9AXEL1Yzh",
	"2y5m7jabUj2NtknX4OuWCPWuvnrbnlucGIH4AefHgk9NHumtuRDY2KPjmFYVTIfF8u52AxkVBm+pslz9",
	"CURjN9egiFgFo1CuMDRNaGyf6hu5zg/ekEIwTtYYqdvfG7v9DbsK2ocvVxnk+Tr7CdQGGNU9inWBbF9D",
	"1b8tcxx3wEkxZL9tZWy2R9MW61n4FMsyPMfv4a8SCtFNj5p7mQ5wm5jZivIqxfFtSvQUKkB2Upk13hta",
	"DtGkYnEwi9bNl7d98nJaLsajKUkhuJTceTHaR7fZWPVmjL8HXPjer+vf0Zf5AxJzUiADLUQKlGF+CwnC",
	"BcJI0UB1YGmsr5xuafVd8oi4HujCvMpe7T3lhSTRneQVTSSgoUBk2plma3JoyjgSc0BxyTlQgWJGBdyL",
	"Gj4rv/xU9Mcsk0aQiwftZfxv1i0Tb9bC/YtIqx0CUE3cHKFUGzgq/LXXNwv9BlDponVgoGPo3aTEv1Wx",
	"dmHb333oeCDHPwx3QU/Pxq/rLatBi3kMuAW3ZHbV0wadg0YDPANDg16NWTuSHnytvCxk+g3PopwNw9tf",
	"GqpG45uizcNt1hywpMASSFtZqpmPjX+Jpz9T9sgVeAxUGHXU0ZmVk9QJzbTMJisebao9WZV6N9h156SO",
	"VcUlJ+LhRmpRj3lGxLycnDN2S+BlKeZ6UjIDUD/Z9z9npmE9ZpyT/wWlcEaS+BVgDtwSmKh/Xdjp/uuP",
	"DxLLiqmMJOppTWkuRG7pDBiIbNYdhi6lpkwDnQocK/hBhkmq1tMIFZhQ4MX/GDdylBJa3h8zPqtpX+hH",
	"6JyZ1uitbGRsTw/17MQ6ItW37TlH/zbbCVWUpUjjFek9wvy42lZYN3Rs+mx0enx6/KOSRg4U52R0Nvrp",
	"+PT4VJmFmCudneCcnLhnOWcguuE/xzNCJeuqpSLKdZhKRmeja9PiZd0gxxxnIIAXo7NPRgF/lcAfahmp",
	"83SMX5uDLa+tarEXtH4addW+clf3neDKnRtLCSv3rm1u5a7O8cJOX8c3BjoLzKVfrO1fp5s1pcqzVKnn",
	"wHEBTXZDOJdOyKXUs/cjTAR4mM6PPkKf5WT0lltlKs9PT61HMNv/nPh88qcpDmrqQ05cqui66JRFo7ek",
	"EJWxoaJUm42RHY606Z9Pf+7aqbU+RJlAU1bSpNHnhZ5BHyu9Pbju5Hh6ZcVtB/3psxR4293qX7vx4NPn",
	"xWdJUnudXL898nqcGQj0Mlen4QKORj8c4GT+jvCxZ/080LnUkguAxgOAV1iiRK2VDEBYnhdedO0AKONR",
	"zgoPNnQJhXCed9Bxrh69VE8GQCNOGYVoylnW64g/a7cGhXjFkodtatHknB41mn3HqphuTLjpYBe7RZmz",
	"vNwZoZb1drDm9UwOgz27pZNv7cxkoYdn9zw0B6p/9wLytXoUBqRMxHrzoXA89aK0C4XmUPV4gkp7saTP",
	"HvQwDgcEn4AvQTymdPdhaJd66iukAXm+SgZgI8ZelJuXHuWawsanX/3ubH8qfkQ335DCwbh5rYAduvmP",
	"1bQPwM2fuAeW+2th2xKxqSzOfeC1yep5faHDjjH8zymh3GPnAadZaWiw5zSKWtV7Voz240L7smJ7psWf",
	"GZ9XT5+mL21euTAsba4lsj+fWl8TEUqbTYvdps6WyQH51ZNv1arbkJzazmDygNQbEF92vTdQj70k3VXE",
	"3WTrfVh5MaDf42bt/Sq8BPF30t+uvYcTbfYV1R6/LuhHkM4fny6IvkfJcNWxtSi5LbtojesAAmt9DKO/",
	"XNHtBhQrl/Yauu+lypZwXp+v8SBdhkgt8uEO3bRfAbcOl8evUZQ8EKE9S/hqrE+2THEPbA5zvzMz3/05",
	"X3MeK1igKA3stjzRLA7Gh558M3sJhhQmGsMzcgcUEVEg0xVhmiB7TbCvWNkTsP1ZSr1XYjeFSh9mQm5s",
	"FS/WYPO4Vc3q+r8E8XdR/m4d0KWNVTtEUs3j0aub1ZFkTxk9RTA9arB1JX4YwdbUEysG20avlUqelQ2l",
	"weoAQ/WJvnJIX8JQnc08+xbIQFXrI93awKFAjCKsQTFGcQpY4hVh+oBwKdiRueIEJSUgwRBGU0xSSJC5",
	"q6RjnReShb5VREmtPiH43e33mYKSG9KCM3gzotthHOhheohgb+wRD+YmVStV7W+Qqly5t88/FfCGd77q",
	"A4VLKS1fXXicJYrQxBgXFyQVah/86mJhXLzjyZqdAfN4vgFz1f93nJawTvek1JjdBjyGbMjepVtsnKIO",
	"JMVXTbsOJw3BlNdL4aAd3cm3eqP9YpDX28DpXTnnX56au2tSapxOOIzAX5/r96O70t/gaG/VtWrhV3F6",
	"Osg/0eErmtd3Byw3hGaf4z7EN28m+KfCPxAbUpIRMTzg78OI2ldWLLUp1R4ZKOzRxFqMD9riosLedjfM",
	"traWX+tb9p5+jr1WQrbzYrMpZY+lVCC/sUqd7Xj5McTxoM2jOvS93DpU061Vn+fVYe7v5rGTaKIFvKTq",
	"cJW6QenRJXOIoDepk3DuWAyi3oQ423ZT2OvQXt3u+B32u4kKvktBPRagm6EPjnJ3HRyCLA/RUMy6STRx",
	"bz4Nmoq9IqhqvamxdO5d/b7KXkO8IxwPvk0b9MrVyK4R3sP0kDE+KBpYiG8rHBhZfY8H+zGWpQHBYnef",
	"ESHM8wDMxb3wqX8Lqm05YBPqtSX6D9uG2v+i5JHfUbhXggV2slq9DTeGqsdh3CphbyPzb0u9rp4+zY2p",
	"zUsDh21NrSWyv/0y1Z1wwe2pRhPD98y0+k3W2K9q77w8IKd78q36rvWQXat2BnUiUnVfunN1b9j3JyDu",
	"97t3s3u1H1Jh17XGDtY9IqlnD+t6aLgE8XeCwq791WUdFXeKLJfPo+9pXQ9ZeufV0wXXI8frpuwPJV6b",
	"DaT7MIGPTfAdaJg+UbdZHy29aETdeJSm9eUSX+bAAeHeG8Z7vLW62nv/N5Ecguv2fjGv7+Pgq39AtnH3",
	"+tm3Jfe5L/8A+GIcvmS527k/7CjNo/OVb0PpmGDP+0wBnOIUFcDvgGvT26nF+e6T0JY1YCFC31ffWI4I",
	"XpzSusPnQrMYYj7rnQkfuh6xyRrE1restKxHX/wf5e3LqgkVPz0fjT23W6uPEK3Qfuu3jEeVtS3l3ro+",
	"O6+XqhoTdyfVZPJ5gP1et66Z0pgtVnvn2uq7x4DYY55DS1YOGburozkujNnKVCdsru9VL9dY92Cre6tU",
	"9eyaeh3uz3Uc4JAqcRVzkg9w7V6Wj1dgmKUY57q8pjdvTu8ZSSDLmXRiqMLJDx3Q3FSX0Dw5xKxXczT9",
	"dTt3aUr8nfoDp0g3UPYn805CZ81PwTjfuXkGx7PjMfqPTAxU9ggFogAJJGhKUigeCgEZKso8Z1wgwdAc",
	"0yQFROFLdSoLTwVwzcG8U/vPSKoO7nGWq1vvHeITwadFRZDYu/KPgM4IhcEcVv4wjzcXWwwx5Yswas03",
	"YmqQJ9bGp2WaPgSXOK/oHU5Jva75DPN4TgTEouSAMlJkWMTzMfrCGZ0hByFjBCI+/mHpRSnOgJc7jpt2",
	"ANpn/AmfH+hbtnC+f+FbmVjpeMAmO/C3v5Dg/dTJsPUERyj7W1DoOyzwsTmu4SlRu+Oe8BhXH5bpu9kY",
	"mWa+C9Lsk93dxBQEhLrBTT0NCkrPcg441Z9a8c5SP0ZAk5wR2j01+0Z3H+I5Dan+4aRsRuhJPAkO6JKI",
	"N+UEvZPKQjFO0wmOb9Ez83PGEkCMpg/dZOGtpHw+GTTUFvWcM4lUjz//6fS5L/VKCIdYBUjGiSwI0vTB",
	"undI0Mf3b4dcyKLb/OgxCIpLMWecfIWVa3vZ+setAVARfV9rtPspHCYQkXE/AyqnLh3Uu6vX50jOQKmr",
	"DwcqLqoP37NbCG9Rs83Qv/74gLD2KqoHeqZ49aDid9P1g2IwBBsVM82hmb17lEVMdJeB9D6Xblj3PAhV",
	"GLMZpIwvMJkzdhs+pG+ImXaDbfIPQ9cfneeA9SlXE5//7+hNOTm6ITOKZXq0VhbfpXmpwsDRr3dAxfbL",
	"PyW/Si7NePcEbPHuR5OHhFWvvtwajhLv5ONRX4ok4F6c3Gfp8Ok2Pha7JCXqDG9QRtSKCYrG+yEXaplR",
	"ITKtcvqCfFUr/4IxlGI+84l6sfj/AAAA///Y+b0zuaUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
